apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-config
  namespace: gemini-namespace
data:
  GOOGLE_ID: 588085719363-hnchrorarf6sfitms5m2bir4suou0sg7.apps.googleusercontent.com
  MONGODB_URI: mongodb://mongodb-service:27017/gemini
  NEXTAUTH_URL: https://72.61.159.174.nip.io
  MONGO_INITDB_ROOT_USERNAME: admin
