apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLXhRaG1BLVdMN0tMRTRoLUJUVDlySnBXYm93T2M=  # Base64 for google key
  NEXTAUTH_SECRET: R09DU1BYLXhRaG1BLVdMN0tMRTRoLUJUVDlySnBXYm93T2MK # Base64 for auth key
  NEXT_PUBLIC_API_KEY: QUl6YVN5QlVtVk0wemdEMFdob29xdnloSFFSTlp5SGszUUNoTHNR # Base64 for api key
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5AMTIzCg==  # Base64 for admin@123
